### PR TITLE
Feat/tweet contents

### PR DESCRIPTION
**Pull request by martinratinaud**
Display similar tweets

### CODE REVIEW

**Comment by clementbiron** [comment]
Can be improved : 

- the hover on filter button displays a message not understandable : `Filter by undefined content`
image

**Comment by clementbiron** [comment]
- tweet content should not be trunck 
 
image

**Comment by clementbiron** [comment]
- when the filtering by a important tweet content, the tag has a bad display
image

**Comment by martinratinaud** [comment]
@clementbiron i've addressed all points and so am merging now

**Pull request merged**
